### ISSUE TITLE
Only app.php by default?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/php-web-cnb#2]
_I understand this project + others are in flux; my question is inquisitive about intent and possibility and am also trying to learn how to write buildpacks; and submit useful PRs along the way_

Historically the php-buildpack supported a range of default entrypoint `.php` scripts, including `index.php` (which is the example in https://docs.cloudfoundry.org/buildpacks/php/index.html).

The current implementation of php-web-cnb only supports `app.php` by default, else I see build error:

```
[builder] -----> PHP Web Buildpack 0.0.4
[builder] -----> Configuring PHP Script
[builder] -----> PHP Web e50003de403a58da1b3e060d24ad101578b1568c: Contributing to layer
[builder]        Writing PHPRC to shared
[builder]        Writing PHP_INI_SCAN_DIR to shared
[builder] WARNING: `app.php` start script not found. App will not start unless you specify a custom start command.
[builder] -----> Process types:
[builder]        task: php /workspace/app.php
[builder]        web:  php /workspace/app.php
```

And a runtime error:

```
Could not open input file: /workspace/app.php
```

This default comes from:

https://github.com/cloudfoundry/php-web-cnb/blob/49e03680fabd32e2f23a4a3ae903d7cc3e379d68/phpweb/phpweb.go#L76-L79

If we wanted to return to supporting more implicit entrypoint scripts (`index.php`), where would we do this? Do we first find `index.php` in `cmd/detect`, and if we find a supported implicit entrypoint then we'd pass it thru in the `phpweb.ScriptDependency: buildplan.Dependency{}`?

**Comment by drnic** [comment]
Weird, maybe I don't know what I'm doing. 

I renamed `index.php` to `app.php` in my tiny PHP app and it still fails:

```
[builder] -----> PHP Web Buildpack 0.0.4
[builder] -----> Configuring PHP Script
[builder] -----> PHP Web e50003de403a58da1b3e060d24ad101578b1568c: Contributing to layer
[builder]        Writing PHPRC to shared
[builder]        Writing PHP_INI_SCAN_DIR to shared
[builder] WARNING: `app.php` start script not found. App will not start unless you specify a custom start command.
[builder] -----> Process types:
[builder]        task: php /workspace/app.php
[builder]        web:  php /workspace/app.php
```

**Comment by drnic** [comment]
Ok, I've moved my `app.php` into `htdocs/app.php` and this error goes away.

**Comment by dmikusa-pivotal** [comment]
>Ok, I've moved my app.php into htdocs/app.php and this error goes away.

This is one of the changes that was made. The buildpack no longer moves files around for you (was a major source of confusion/issues with the v2 PHP buildpack). It expects some sort of public, static, htdocs web directory to exist (directory name configurable through buildpack.yml).

If you do not supply that, then it assumes you're not pushing a web app. That's why you were seeing this output initially:

```
[builder] WARNING: `app.php` start script not found. App will not start unless you specify a custom start command.
[builder] -----> Process types:
[builder]        task: php /workspace/app.php
[builder]        web:  php /workspace/app.php
```

**Comment by dmikusa-pivotal** [comment]
>Historically the php-buildpack supported a range of default entrypoint .php scripts, including index.php (which is the example in https://docs.cloudfoundry.org/buildpacks/php/index.html).

The default entry point for a command line PHP app is `app.php`, but you can override this by setting a `script` name in `buildpack.yml`. That will be relative to the application root.

https://github.com/cloudfoundry/php-web-cnb/blob/master/phpweb/phpweb.go#L69

For web apps, it's different. The start command generated will either be the internal PHP web server or an external web server + PHP-FPM, depending on what web server CNBs you have available. HTTPD & Nginx are likely targets. As I mentioned in my previous comment, the web server would be configured to serve public files from the web directory that is configured.
